name: conflibot
on: pull_request_target

jobs:
  conflibot:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Warn potential conflicts
        uses: wktk/conflibot@v1
        with:
          github-token: ${{ secrets.TOKEN }}
