name: conflibot
on: pull_request

jobs:
  conflibot:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Warn potential conflicts
        uses: wktk/conflibot@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN || secrets.MY_TOKEN }}
          exclude: |
            yarn.lock
